import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "~/utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.useQuery(["hello", { text: "sir" }]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1 className="text-3xl font-bold underline">{hello.data?.greeting}</h1>
      </div>
    </>
  );
};

export default Home;
