import type { NextPage } from "next";
import Head from "next/head";
import Feed from "~/components/Feed";
import PostBox from "~/components/PostBox";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="my-7 mx-auto max-w-5xl">
        <PostBox />

        <div className="flex">
          <Feed />
        </div>
      </div>
    </>
  );
};

export default Home;
